./host_inference_native_lite_transformer_encoder_baseline \
	models/lite_transformer_encoder/lite-transformer-encoder-16-c1-1.rknn \
	models/lite_transformer_encoder/lite-transformer-encoder-16-b1-2.rknn \
	models/lite_transformer_encoder/lite-transformer-encoder-16-b1-3.rknn \
	models/lite_transformer_encoder/lite-transformer-encoder-16-b1-4.rknn \
	models/lite_transformer_encoder/lite-transformer-encoder-16-c1-4.rknn \
	models/lite_transformer_encoder/lite-transformer-encoder-16-c1-6.rknn \
	models/lite_transformer_encoder/lite-transformer-encoder-16-b2-2.rknn \
	models/lite_transformer_encoder/lite-transformer-encoder-16-b2-3.rknn \
	models/lite_transformer_encoder/lite-transformer-encoder-16-b2-4.rknn \
	models/lite_transformer_encoder/lite-transformer-encoder-16-c2-4.rknn \
	models/lite_transformer_encoder/lite-transformer-encoder-16-c2-6.rknn \
	models/lite_transformer_encoder/lite-transformer-encoder-16-b3-2.rknn \
	models/lite_transformer_encoder/lite-transformer-encoder-16-b3-3.rknn \
	models/lite_transformer_encoder/lite-transformer-encoder-16-b3-4.rknn \
	models/lite_transformer_encoder/lite-transformer-encoder-16-c3-4.rknn \
	models/lite_transformer_encoder/lite-transformer-encoder-16-c3-6.rknn \
	models/lite_transformer_encoder/lite-transformer-encoder-16-b4-2.rknn \
	models/lite_transformer_encoder/lite-transformer-encoder-16-b4-3.rknn \
	models/lite_transformer_encoder/lite-transformer-encoder-16-b4-4.rknn \
	models/lite_transformer_encoder/lite-transformer-encoder-16-c4-4.rknn \
	models/lite_transformer_encoder/lite-transformer-encoder-16-c4-6.rknn \
	models/lite_transformer_encoder/lite-transformer-encoder-16-b5-2.rknn \
	models/lite_transformer_encoder/lite-transformer-encoder-16-b5-3.rknn \
	models/lite_transformer_encoder/lite-transformer-encoder-16-b5-4.rknn \
	models/lite_transformer_encoder/lite-transformer-encoder-16-c5-4.rknn \
	models/lite_transformer_encoder/lite-transformer-encoder-16-c5-6.rknn \
	models/lite_transformer_encoder/lite-transformer-encoder-16-c1-3.tflite \
	models/lite_transformer_encoder/lite-transformer-encoder-16-c1-5.tflite \
	models/lite_transformer_encoder/lite-transformer-encoder-16-c2-3.tflite \
	models/lite_transformer_encoder/lite-transformer-encoder-16-c2-5.tflite \
	models/lite_transformer_encoder/lite-transformer-encoder-16-c3-3.tflite \
	models/lite_transformer_encoder/lite-transformer-encoder-16-c3-5.tflite \
	models/lite_transformer_encoder/lite-transformer-encoder-16-c4-3.tflite \
	models/lite_transformer_encoder/lite-transformer-encoder-16-c4-5.tflite \
	models/lite_transformer_encoder/lite-transformer-encoder-16-c5-3.tflite \
	models/lite_transformer_encoder/lite-transformer-encoder-16-c5-5.tflite \
	100
